### PR TITLE
Add support for custom renderer

### PR DESCRIPTION
**Pull request by PhilippRaab**
This pull request allows to pass a function to customize the rendering of the autocompletion dropdown elements.

### CODE REVIEW

**Comment by marijnh** [comment]
What do you want to use this for, specifically?

**Comment by PhilippRaab** [comment]
We want to render React components inside the autocomplete dropdown, that way we can use components of our design system and a custom structure (e.g. a second icon).

**Comment by marijnh** [comment]
I am not a fan of this. There shouldn't be enough complexity in completion items to warrant the use of react or similar. You might be able to display a second icon with some additional CSS.

(Also, the async part of this doesn't work—if you append the element in a `then` the order of the completions will be wrong.)

**Comment by PhilippRaab** [comment]
> I am not a fan of this. There shouldn't be enough complexity in completion items to warrant the use of react or similar

We want to include multiple completion sources. For each item we want to include the source and the number of uses as well as a type icon.

> You might be able to display a second icon with some additional CSS.

Can you explain how that would work?

> (Also, the async part of this doesn't work—if you append the element in a then the order of the completions will be wrong.)

Not sure if it would be needed anyway, i can remove that.

**Comment by marijnh** [comment]
> Can you explain how that would work?

You can add extra classes to the icon element with the `type` field, and then target those with `:before` rules or similar. But displaying a number or other parameterized information in this way will be awkward.

**Comment by PhilippRaab** [comment]
> But displaying a number or other parameterized information in this way will be awkward.

That's why we want to pass the data as part of the completion and then render it with the custom renderer. I think it add a lot of flexibility and it doesn't create too much overhead at runtime and in code maintenance.

**Comment by marijnh** [comment]
I think an approach where we allow the extension to be configured to render additional stuff into the completions might be less problematic. That way you can do something like this without breaking things like the highlighting of matched characters in the completions. Basically, you'd be able to configure `{position: number, render: (completion: Completion, state: EditorState) => Node}` objects that get ran for every rendered completion and can add stuff (with `position` determining the position relative to the other elements in a completion). Does that sound like it might help?

**Comment by PhilippRaab** [comment]
Sounds like a good approach. For the position i guess it would be enough to render something before and after the completion.

**Comment by marijnh** [comment]
Could you take a look at patch d396c01, and let me know if it addresses your use case?

**Comment by PhilippRaab** [comment]
Thank you, that will work for us!

**Comment by marijnh** [comment]
I've released this in 0.19.3

**Pull request closed without merging**
