### PR TITLE
Allow completion detail to accept a Node

### PR DESCRIPTION
**Pull request by nchen63**
Allows more complex styling of the text inside the completion detail.

### CODE REVIEW

**Comment by marijnh** [comment]
What kind of styling are you planning to use this for? I'm somewhat weary of adding complex data structures like DOM nodes to completion objects, since when there are a lot of completions that could easily become a performance issue.

**Comment by nchen63** [comment]
I’d like to add the type’s name with different colors for different types
and a short description in a different font. Since this is opt-in, we can
test for perf issues and it won’t affect other people who don’t use it. CM5
had the ability to do this, and having this allows us to migrate in a more
straightforward way.

**Comment by marijnh** [comment]
[`optionClass`](https://codemirror.net/docs/ref/#autocomplete.autocompletion^config.optionClass) can be used to add additional classes to the completion element based on its content (and thus to style the label and the detail text in a custom way). Would that help?

**Comment by nchen63** [comment]
It looks like this gives the ability to add a class for the whole
completion, but not the ability to have separate styles within the detail
text (in my case, the type name and description).

**Comment by marijnh** [comment]
Right, but those already have other classes (`cm-completionLabel` and `cm-completionInfo`) that you can target with a scoped rule, no?

**Comment by nchen63** [comment]
Here's some examples of what I would like to do, which I can't do by using the other classes:

image

image

**Comment by marijnh** [comment]
I see. [`addToOptions`](https://codemirror.net/docs/ref/#autocomplete.autocompletion^config.addToOptions) is what you want there, I think. Add a new element to options that is rendered based on some extra information you put in the completion object.

**Comment by nchen63** [comment]
Looks like this is what I need. Thanks.

**Pull request closed without merging**
